### ISSUE TITLE
ORA-01727 error when creating the disk quota DB in Oracle

### ISSUE THREAD

**Issue by tdipisa** [GeoWebCache/geowebcache#364]
There is a problem configuring the Disk Quota DB in Oracle.

GeoWebCache Version
1.7.3 (rev a09f77d3b14d4bbcee3feb407fd2d8ea2cf62d64/a09f77d3b14d4bbcee3feb407fd2d8ea2cf62d64)

Oracle Version
11g

When creating the DB tables, Oracle returns the following error:

org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [CREATE TABLE TILEPAGE (
 KEY VARCHAR(320) PRIMARY KEY,
 TILESET_ID VARCHAR(320) REFERENCES TILESET(KEY) ON DELETE CASCADE,
 PAGE_Z SMALLINT,
 PAGE_X INTEGER,
 PAGE_Y INTEGER,
 CREATION_TIME_MINUTES INTEGER,
 FREQUENCY_OF_USE FLOAT,
 LAST_ACCESS_TIME_MINUTES INTEGER,
 FILL_FACTOR FLOAT,
 NUM_HITS NUMBER(64)
) ORGANIZATION INDEX]; nested exception is java.sql.SQLSyntaxErrorException: ORA-01727: numeric precision specifier is out of range 1 to 38

I think the problem is the NUM_HITS column definition (NUM_HITS NUMBER(64)). 
Looking at the Oracle documentation the NUMBER datatype precision can range from 1 to 38.

**Comment by aaime** [comment]
Hi, I've verified that this issue is a regression caused by this commit by @smithkm :+1: 
https://github.com/GeoWebCache/geowebcache/commit/a9eed62979cc9891411e4a8e585f9ca2e7cb9cee

In particular, this is the line:
https://github.com/GeoWebCache/geowebcache/commit/a9eed62979cc9891411e4a8e585f9ca2e7cb9cee#diff-2c01bc986a7691e4a14be621b748d2e2L58

The old code was correctly specifying 38, by extracting constants shared among databases the code ended up using the same value as postgresql.

@smithkm do you prefer that we undo the constants, or should we drop their usage for Oracle only? All numeric fields must go back to 38.

**Comment by smithkm** [comment]
I'm thinking a good way to make it very clear what's going on (so well intentioned refactorers don't break things the same way I did) would be to have a static method that clamps numeric precision to 38.

**Comment by aaime** [comment]
As an alternative, recognize those values might be DB dependent, and have methods returning the values that the specific dialect can override

**Comment by smithkm** [comment]
I've done it via the single clamping method, if you'd prefer to do it using separate overridable methods for each field you can close my request.

**Comment by aaime** [comment]
Fix backported to 1.8.x and 1.7.x too
