### ISSUE TITLE
WMTS getcapabilites document returns null

### ISSUE THREAD

**Issue by nitinlkoin1984** [GeoWebCache/geowebcache#477]
I am trying to access capabilites document for wmts from the following url
http://<server-address>/geoserver/gwc/service/wmts?REQUEST=GetCapabilities

The url returns 400: null
How can I solve this problem

**Comment by smithkm** [comment]
Could not replicate.  Please try posting to the GeoServer Users or GeoWebcache Users mailing list with details about how you have set things up and any details included in the error message or in your logs from when it happend. If it turns out to be a bug, it can be filed her or in the GeoServer Jira bug tracker as appropriate (If it's a bug, it may be a bug in GWC, or in how GS uses GWC)
